#●━━━━━━━━━━━━━━━━━━ TourGoldPlate v2.1 ━━━━━━━━━━━━━━━━━━●
# Ивент «Золотая Плита»
# Права на настройку: tourgoldplate.setup
#●━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━●

enabled: false

#●━━━━━━━━━━━━━━━━━━ Местоположение плиты ━━━━━━━━━━━━━━━━━━●
# ПКМ по плите лопатой gp wand
plate:
  world: null
  x: 0
  y: 0
  z: 0

#●━━━━━━━━━━━━━━━━━━ Настройки награды ━━━━━━━━━━━━━━━━━━●
reward:
  # FIXED — фиксированная сумма каждый тик
  # PER_ONLINE — зависит от кол-ва онлайн игроков
  type: FIXED

  # Интервал в тиках (20 тиков = 1 секунда, минимум 3)
  tick: 20

  fixed:
    amount: 10

  per-online:
    # Итого = base + (кол-во_игроков × each-player)
    base: 10
    each-player: 5

#●━━━━━━━━━━━━━━━━━━ Звук ━━━━━━━━━━━━━━━━━━●
sound:
  enabled: true
  # Имя звука из списка Bukkit Sound
  name: ENTITY_EXPERIENCE_ORB_PICKUP
  volume: 1.0
  pitch: 1.2
